################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
Third\ Party/LWIP/src/core/def.obj: ../Third\ Party/LWIP/src/core/def.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/def.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/dhcp.obj: ../Third\ Party/LWIP/src/core/dhcp.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/dhcp.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/dns.obj: ../Third\ Party/LWIP/src/core/dns.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/dns.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/init.obj: ../Third\ Party/LWIP/src/core/init.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/init.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/mem.obj: ../Third\ Party/LWIP/src/core/mem.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/mem.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/memp.obj: ../Third\ Party/LWIP/src/core/memp.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/memp.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/netif.obj: ../Third\ Party/LWIP/src/core/netif.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/netif.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/pbuf.obj: ../Third\ Party/LWIP/src/core/pbuf.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/pbuf.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/raw.obj: ../Third\ Party/LWIP/src/core/raw.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/raw.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/stats.obj: ../Third\ Party/LWIP/src/core/stats.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/stats.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/sys.obj: ../Third\ Party/LWIP/src/core/sys.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/sys.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/tcp.obj: ../Third\ Party/LWIP/src/core/tcp.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/tcp.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/tcp_in.obj: ../Third\ Party/LWIP/src/core/tcp_in.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/tcp_in.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/tcp_out.obj: ../Third\ Party/LWIP/src/core/tcp_out.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/tcp_out.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/timers.obj: ../Third\ Party/LWIP/src/core/timers.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/timers.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/core/udp.obj: ../Third\ Party/LWIP/src/core/udp.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/core/udp.d_raw" --obj_directory="Third Party/LWIP/src/core" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


