################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
Third\ Party/LWIP/src/api/api_lib.obj: ../Third\ Party/LWIP/src/api/api_lib.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/api/api_lib.d_raw" --obj_directory="Third Party/LWIP/src/api" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/api/api_msg.obj: ../Third\ Party/LWIP/src/api/api_msg.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/api/api_msg.d_raw" --obj_directory="Third Party/LWIP/src/api" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/api/err.obj: ../Third\ Party/LWIP/src/api/err.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/api/err.d_raw" --obj_directory="Third Party/LWIP/src/api" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/api/netbuf.obj: ../Third\ Party/LWIP/src/api/netbuf.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/api/netbuf.d_raw" --obj_directory="Third Party/LWIP/src/api" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/api/netdb.obj: ../Third\ Party/LWIP/src/api/netdb.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/api/netdb.d_raw" --obj_directory="Third Party/LWIP/src/api" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/api/netifapi.obj: ../Third\ Party/LWIP/src/api/netifapi.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/api/netifapi.d_raw" --obj_directory="Third Party/LWIP/src/api" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/api/sockets.obj: ../Third\ Party/LWIP/src/api/sockets.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/api/sockets.d_raw" --obj_directory="Third Party/LWIP/src/api" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Third\ Party/LWIP/src/api/tcpip.obj: ../Third\ Party/LWIP/src/api/tcpip.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/lwip/ipv4" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/ipv4/lwip" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/system/arch" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/netif" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix" --include_path="C:/Users/mfathy/workspace_v9_2/lwip_1/Third Party/LWIP/src/include/posix/sys" --include_path="D:/ti/TivaWare_C_Series-2.1.4.178" --include_path="D:/ti/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --define=ccs="ccs" --define=__packed=__attribute__((__packed__)) --define=PART_TM4C123GH6PM -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Third Party/LWIP/src/api/tcpip.d_raw" --obj_directory="Third Party/LWIP/src/api" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


